version: '3.3'

services:
  websocket_server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4109:4109"
    volumes:
      - ./:/var/www/html/
    command: /start.sh
    restart: unless-stopped
